### ISSUE TITLE
Toggleable cooldown period for commands when player is in combat

### ISSUE THREAD

**Issue by stahlfaust** [EternalFlame06/WarpUtils-Issues#11]
### Feature Description

I am running a Fabric server and I have a PvP arena set up, but I would like to be able to prevent players from teleporting away until they have been out of combat for a certain period if time. I know TPA probably already has this feature but I wasn't sure if /back, /warp, /home, etc did.

**Comment by EternalFlame06** [comment]
The mod doesn't directly have the feature that prevents you from teleporting out of the arena. I can add it if you want, but my time this week is very limited so maybe after that. 

Alternatively you could enable a delay for each feature, so you have to stand still for a short duration. So when you are attacked you move and the teleportation cancels.

**Comment by stahlfaust** [comment]
That's a good idea. Could you implement both? I'm in no hurry and would be very grateful. If you only have energy for one feature I think I would still choose my original request.

**Comment by EternalFlame06** [comment]
The delay is already implemented.

Use /warputils config <feature> delay <timeInTicks>

to set the delay.

or you could set the delay for every feature to -1 and set the general delay to the delay you want. This way all delays use the centralized general delay. This should be the default but I think the delay period is rather short, only 1.5 seconds (30 ticks).

**Comment by EternalFlame06** [comment]
I hope I met your expectations with version 0.3.3, even though it took a bit longer than expected to update the mod.
