### ISSUE TITLE
Sonic Boom Effect crashes servers when selected

### ISSUE THREAD

**Issue by TekkyNeko** [EternalFlame06/WarpUtils-Issues#13]
### Bug Description

When one of my friends selected the Sonic boom teleport effect, every time he had teleported via TPA and home, the server proceeds to crash. This could be a mod conflict but I'm not sure, log file provided 

### Reproduction Steps

1. create a 1.21 fabric server with warputils installed
2. select SonicBoom as your arrival and/or teleport effect
3. teleport anywhere (via warp, tpa, or home)
4. witness the crash

### Log File

[2024-07-25-3.log](https://github.com/user-attachments/files/16386742/2024-07-25-3.log)

**Comment by EternalFlame06** [comment]
It seems like the sound effect causes the crash. I will remove it later or maybe find a solution, as soon as I recreated the crash.

**Comment by EternalFlame06** [comment]
Thanks for the report btw. In version 0.3.2 the crash should happen anymore, because I removed the sound effect. I may add it in again in the future if I find a solution that works in all the versions the mod supports.
