### ISSUE TITLE
TPA doesn't work

### ISSUE THREAD

**Issue by masuteri** [EternalFlame06/WarpUtils-Issues#4]
### Bug Description

![kuva](https://github.com/EternalFlame06/WarpUtils-Issues/assets/80328342/c81da0b8-a48d-47ac-8821-4087afa39bbe)
TPA doesn't work.

### Reproduction Steps

Install the plugin on your server, enable it, and it simply doesn't work

### Log File

[2024-03-03-8.log.gz](https://github.com/EternalFlame06/WarpUtils-Issues/files/14483939/2024-03-03-8.log.gz)
(ignore the heightmap warning. We have a datapack increasing the height limit. The mod also doesn't also give any indication to the console that it's being used)

**Comment by EternalFlame06** [comment]
I am not sure if that is the problem, but when testing I found that the duration of tpas isn't infinite as it is supposed to be when setting it to 0 in the settings. So until I fix this bug you could increase the duration.

**Comment by EternalFlame06** [comment]
Should be fixed in 0.2.5
