### ISSUE TITLE
Tpa does not work.

### ISSUE THREAD

**Issue by xmaniaxz** [EternalFlame06/WarpUtils-Issues#6]
### Bug Description

Users cant use Tpa.  they either get an unexpected error that says the playerName is missing as argument. 
But when using an argument it says it is a Incorrect argument.

### Reproduction Steps

/tpa > An unexpected error occured trying to execute that commend > hover > No such argument "playerName" exists in that command
/tpa (correct username) > Incorrect argument for command

### Log File

no logs exist

**Comment by EternalFlame06** [comment]
The bug should be fixed. I accidentally lowered the number of arguments to 0 when cleaning up a bit of my code.

**Comment by xmaniaxz** [comment]
Confirmed, this is now fixed
